language: python

python:
  - 3.5

sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.14.0

before_install:
  - docker-compose run -d sshd
  - docker network inspect autologger_logger_net
  - docker inspect autologger_sshd_run_1
  - ip addr

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=logger setup.py test

after_success:
  coveralls
