sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.14.0

python:
  - 3.5

before_install:
  - docker-compose run -d sshd

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=logger setup.py test

after_success:
  coveralls
