language: python

python:
  - 3.4

sudo: false

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.14.0

cache:
  directories:
  - "$HOME/.pip-cache/"

before_install:
  - chmod 600 sshd/.ssh/id_rsa
  - cp sshd/.ssh/id_rsa ~/.ssh/id_rsa
  - docker-compose -f docker-compose.travis.yml run -d sshd

install:
  - pip install -r requirements.txt --cache-dir $HOME/.pip-cache
  - pip install coveralls

script:
  - coverage run --source=logger setup.py test

after_success:
  coveralls
