language: python
python:
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - cp tests/plog.ini ./
  - coverage run --source=logger setup.py test
after_success:
  coveralls
